### ISSUE TITLE
Question: no resolver found for absolute URL

### ISSUE THREAD

**Issue by mdgbayly** [PolymerLabs/polylint#141]
If you include an absolute URL in a web component link then polylint fails with a no resolver found error.
Is this expected? Is there a workaround? Is it an anti-pattern to link to a polymer resource on a CDN?

e.g. following the examples here: https://www.polymer-project.org/1.0/docs/devguide/quick-tour, the examples include an absolute URL ref for polymer
`<link rel="import"  href="https://polygit2.appspot.com/components/polymer/polymer.html">`

But this fails to lint with the error:

`Error: no resolver found for https://polygit2.appspot.com/components/polymer/polymer.html
    at FileLoader.request 
<snip>
(C:\Users\mbayly\AppData\Roaming\npm\node_modules\polylint\node_modules\hydrolysis\lib\loader\file-loader.js:70:37)
    at Analyzer.load (C:\Users\mbayly\AppData\Roaming\npm\node_modules\polylint\node_modules\hydrolysis\lib\analyzer.js:121:32)
    at Analyzer._getDependencies (C:\Users\mbayly\AppData\Roaming\npm\node_modules\polylint\node_modules\hydrolysis\lib\analyzer.js:433:25)
    at Analyzer._dependenciesLoadedFor (C:\Users\mbayly\AppData\Roaming\npm\node_modules\polylint\node_modules\hydrolysis\lib\analyzer.js:401:25)
    at Analyzer._parseHTML (C:\Users\mbayly\AppData\Roaming\npm\node_modules\polylint\node_modules\hydrolysis\lib\analyzer.js:227:50)
    at null._onTimeout (C:\Users\mbayly\AppData\Roaming\npm\node_modules\polylint\node_modules\hydrolysis\lib\analyzer.js:125:39)
    at Timer.listOnTimeout (timers.js:92:15)
`

**Comment by vdhpieter** [comment]
+1

**Comment by pdesjardins90** [comment]
It must be a bug, if you install the official google-chart component, this error pops up for https://www.gstatic.com/charts/loader.js

**Comment by ryantmer** [comment]
@mdgbayly It looks like this has been fixed in the more recent versions of https://github.com/Polymer/polymer-linter :)
