### ISSUE TITLE
npm install -g polylint not working

### ISSUE THREAD

**Issue by danielbaak** [PolymerLabs/polylint#26]
I'm not sure if my setup is broken in some way, but this only happens with polylint so I figured I'd post it here.

```
npm install -g polylint
npm ERR! git clone git://github.com/justinfagnani/polymer-expressions.git Cloning into bare repository '/home/user/.npm/_git-remotes/git-github-com-justinfagnani-polymer-expressions-git-e1fd43eb'...
npm ERR! git clone git://github.com/justinfagnani/polymer-expressions.git fatal: unable to connect to github.com:
npm ERR! git clone git://github.com/justinfagnani/polymer-expressions.git github.com[0: 192.30.252.130]: errno=Connection refused
npm ERR! Error: Command failed: Cloning into bare repository '/home/user/.npm/_git-remotes/git-github-com-justinfagnani-polymer-expressions-git-e1fd43eb'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.130]: errno=Connection refused
npm ERR! 
npm ERR! 
npm ERR!     at ChildProcess.exithandler (child_process.js:658:15)
npm ERR!     at ChildProcess.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:766:16)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.13.0-37-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "polylint"
npm ERR! cwd /tmp
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code 128
npm ERR! not ok code 0
```

Is anyone else experiencing this type of "couldn't connect to github ..." error?

**Comment by danielbaak** [comment]
The issue was caused by my home router's blocking of port 22. The command works just fine on non-restricted networks
