### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by markhuang1212** [PolymerLabs/polylint#27]
```
D:\large-screen-only\large-screen-only>polylint
C:\Users\Mark Huang\AppData\Roaming\npm\node_modules\polylint\bin\polylint.js:86
if (!inputs.length) {
           ^
TypeError: Cannot read property 'length' of undefined
    at Object.<anonymous> (C:\Users\Mark Huang\AppData\Roaming\npm\node_modules\polylint\bin\polylint.js:86:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by garlicnation** [comment]
Fixed with 2.1.0
