### ISSUE TITLE
polylint crashes when adding a @pseudoElement to an element

### ISSUE THREAD

**Issue by ronnyroeller** [PolymerLabs/polylint#94]
I accidentally added a @pseudoElement annotation to an element.

```
<!--
@pseudoElement my-element
@demo demo/index.html
-->
<dom-module id="my-element">
	<template>
```

This crashed polylint with a TypeError:

```
$ polylint
TypeError: Cannot read property 'nodeName' of undefined
    at isCommentNode (...\npm\node_modules\polylint\node_modules\dom5\dom5.js:282:14)
    at Object.getTextContent (...\npm\node_modules\polylint\node_modules\dom5\dom5.js:153:7)
    at ...\npm\node_modules\polylint\lib\linters.js:441:32
    at Array.forEach (native)
    at domModuleAfterPolymer (...\npm\node_modules\polylint\lib\linters.js:427:23)
    at ...\npm\node_modules\polylint\polylint.js:42:22
```

It would be better if polylint would state at least the element at which the error occured and ideally also that the error was caused by a forbidden annotation.

**Comment by lassecapel** [comment]
Looks like this is [fixed](https://github.com/Polymer/polymer-analyzer/pull/409) in 'polymer-analyzer'. 

Not sure if this repo will be updated to use `polymer-analyzer` instead of `hydrolysis`. I think it will be implemented in the new [polymer-linter](https://github.com/Polymer/polymer-linter)
